export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMER_SUCCESS = "GET_CUSTOMER_SUCCESS";
export const GET_CUSTOMER_FAILURE = "GET_CUSTOMER_FAILURE";

export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

// export const CHANGE_NAME = "CHANGE_NAME";
// export const CHANGE_EMAIL = "CHANGE_EMAIL";
// export const CHANGE_MOBILE = "CHANGE_MOBILE";

export const CHANGE_INPUT = "CHANGE_INPUT";

export const SUBMIT_CUSTOMER = "SUBMIT_CUSTOMER";
